[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts = --tracing=retain-on-failure

markers =
    smoke: Smoke test suite
    regression: Regression test suite
    critical: Critical business flows
    login: Authentication features
    cart: Shopping cart features
    mobile: Mobile application tests